[book]
title = "Miniweather Station Dashboard Documentation"
author = "In'am Nurul Fuady"
language = "en"
src = "src"

[build]
build-dir = "docs"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
